[build]
  publish = "."
  command = "echo 'Site estático pronto para deploy'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.cartola.globo.com https://fonts.googleapis.com https://fonts.gstatic.com;"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.csv"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/api/*"
  to = "https://api.cartola.globo.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[dev]
  command = "python -m http.server 8002"
  port = 8002
  publish = "."