[build]
  publish = "."
  command = "echo 'Site estático pronto para deploy'"
  functions = "netlify/functions"

# Configuração para as funções serverless
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers globais para CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Redirecionamentos para a função da API
[[redirects]]
  from = "/api/cartola/*"
  to = "/.netlify/functions/cartola-api?endpoint=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/cartola"
  to = "/.netlify/functions/cartola-api"
  status = 200
  force = true

# Headers específicos para a API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Headers para arquivos estáticos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.csv"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/csv"

[dev]
  command = "python -m http.server 8002"
  port = 8002
  publish = "."
